import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const menu = [
  { id:'classic', name:'Classic Zippolino', note:'Butter & icing sugar.', price:5, tone:'vanilla', icon:'✦' },
  { id:'nutella', name:'Nutella Dream', note:'Nutella & icing sugar.', price:7, tone:'cocoa', icon:'N' },
  { id:'strawberry', name:'Strawberry Kiss', note:'Fresh strawberries & chocolate drizzle.', price:7.5, tone:'berry', icon:'S' },
  { id:'lotus', name:'Lotus Heaven', note:'Lotus Biscoff spread & biscuit crumbs.', price:7.5, tone:'caramel', icon:'L' },
  { id:'banana', name:'Banana Bliss', note:'Fresh banana & chocolate drizzle.', price:7.5, tone:'hazel', icon:'B' },
  { id:'pistachio', name:'Pistachio Royale', note:'Premium pistachio cream & crushed pistachios.', price:9, tone:'pistachio', icon:'P' },
  { id:'oreo', name:'Oreo Explosion', note:'Oreo crumbs & chocolate sauce.', price:7.5, tone:'oreo', icon:'O' },
  { id:'dubai', name:'Dubai Delight', note:'Pistachio cream, crispy kunafa & chocolate drizzle.', price:9.5, tone:'dubai', icon:'D' }
];
const drinks = {
  Coffee:['Espresso','Americano','Cappuccino','Latte','Iced Latte'],
  'Cold Drinks':['Coca-Cola','Coca-Cola Zero','Sprite','Fanta Orange','Still Water']
};
const options = {
  size:[['Mini Treat · 8 Mini Pancakes',0],['Regular · 12 Mini Pancakes · Most Popular',2],['Large · 18 Mini Pancakes',5],['Sharing Box · 30 Mini Pancakes',10]],
  sauce:[['As described',0],['Nutella',1],['White chocolate',1],['Pistachio',2],['Lotus Biscoff',1],['Caramel',.75]],
  extra:[['No extra',0],['Strawberries',1.5],['Banana',1],['Oreo crunch',1],['Lotus crumb',1],['Bueno pieces',1.5],['Kunafa crunch',1.5]]
};
const money = n => `€${n.toFixed(2)}`;
const event = (name,data={}) => { window.dataLayer?.push({event:name,...data}); };

function App(){
  const [cart,setCart] = useState(()=>JSON.parse(localStorage.getItem('zippolino-cart')||'[]'));
  const [product,setProduct] = useState(null);
  const [choice,setChoice] = useState({size:1,sauce:[],extra:[],qty:1,note:''});
  const [cartOpen,setCartOpen] = useState(false);
  const [checkout,setCheckout] = useState(false);
  const [confirmation,setConfirmation] = useState(null);
  const [admin,setAdmin] = useState(location.hash==='#orders');
  useEffect(()=>{localStorage.setItem('zippolino-cart',JSON.stringify(cart));},[cart]);
  useEffect(()=>{const f=()=>setAdmin(location.hash==='#orders'); addEventListener('hashchange',f); return()=>removeEventListener('hashchange',f)},[]);
  const count=cart.reduce((a,x)=>a+x.qty,0), subtotal=cart.reduce((a,x)=>a+x.total,0);
  const openProduct=p=>{setProduct(p);setChoice({size:1,sauce:[],extra:[],qty:1,note:''});event('view_item',{item_id:p.id});};
  const toggleChoice=(group,index)=>setChoice(c=>({...c,[group]:index===0?[]:c[group].includes(index)?c[group].filter(i=>i!==index):[...c[group],index]}));
  const add=()=>{const size=options.size[choice.size],sauces=choice.sauce.map(i=>options.sauce[i]),extras=choice.extra.map(i=>options.extra[i]);const unit=product.price+size[1]+sauces.reduce((sum,x)=>sum+x[1],0)+extras.reduce((sum,x)=>sum+x[1],0);const item={key:crypto.randomUUID(),id:product.id,name:product.name,size:size[0],sauce:sauces.length?sauces.map(x=>x[0]).join(', '):'As described',extra:extras.length?extras.map(x=>x[0]).join(', '):'No extra',note:choice.note,qty:choice.qty,unit,total:unit*choice.qty};setCart(c=>[...c,item]);event('add_to_cart',{item_id:product.id,value:item.total});setProduct(null);setCartOpen(true)};
  const submitOrder=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const order={id:`ZIP-${Date.now().toString().slice(-6)}`,createdAt:new Date().toISOString(),status:'New',items:cart,total:subtotal,customer:data};const orders=JSON.parse(localStorage.getItem('zippolino-orders')||'[]');localStorage.setItem('zippolino-orders',JSON.stringify([order,...orders]));event('purchase',{transaction_id:order.id,value:subtotal,currency:'EUR'});const api=import.meta.env.VITE_ORDER_API_URL;if(api){try{await fetch(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(order)})}catch{}}const payment=import.meta.env.VITE_PAYMENT_URL;if(payment){location.href=`${payment}?reference=${order.id}&amount=${subtotal.toFixed(2)}`;return}setConfirmation(order);setCart([]);setCheckout(false);setCartOpen(false)};
  if(admin) return <Orders/>;
  return <>
    <header><a className="brand" href="#top"><span>Z</span>ZIPPOLINO</a><nav><a href="#menu">Menu</a><a href="#story">Our story</a><a href="#visit">Visit</a></nav><button className="cart-btn" onClick={()=>setCartOpen(true)}>Bag <b>{count}</b></button></header>
    <main id="top">
      <section className="hero">
        <div className="hero-copy"><p className="eyebrow">DUTCH MINI PANCAKES · PAPHOS</p><h1>Little pancakes.<br/><em>Big happiness.</em></h1><p className="intro">Made fresh. Dressed lavishly. Devoured happily. Meet Cyprus' most irresistible little luxury.</p><a className="primary" href="#menu">Explore the menu <span>↘</span></a><div className="proof"><span>MADE TO ORDER</span><span>PREMIUM INGREDIENTS</span><span>ONLINE ONLY</span></div></div>
        <div className="hero-art"><div className="plate"><div className="pancakes">{Array.from({length:12},(_,i)=><i key={i}/>)}</div><div className="drizzle"/></div><div className="stamp">FRESH<br/>DAILY</div><p className="art-label">Soft. Golden. Generously topped.</p></div>
      </section>
      <section className="marquee"><div>POFFERTJES ✦ MADE FRESH ✦ SWEET MOMENTS ✦ POFFERTJES ✦ MADE FRESH ✦ SWEET MOMENTS ✦</div></section>
      <section id="menu" className="menu"><div className="section-head"><div><p className="eyebrow">THE MAIN EVENT</p><h2>Pick your pleasure.</h2></div><p>Every box starts with warm, pillowy Dutch mini pancakes, finished to order.</p></div><div className="grid">{menu.map((p,i)=><article className={`product ${p.tone}`} key={p.id} onClick={()=>openProduct(p)}><div className="food"><span>{p.icon}</span><div className="mini-stack">{Array.from({length:7},(_,j)=><i key={j}/>)}</div></div><div className="product-info"><small>0{i+1}</small><h3>{p.name}</h3><p>{p.note}</p><div><b>from {money(p.price)}</b><button aria-label={`Customise ${p.name}`}>+</button></div></div></article>)}</div>
      </section>
      <section className="builder"><div><p className="eyebrow">YOUR RULES</p><h2>Build your own<br/><em>little masterpiece.</em></h2><p>Choose the size, the sauce and the finishing crunch. There are no wrong answers here.</p><button className="primary" onClick={()=>openProduct({id:'custom',name:'Build Your Own',note:'Your pancakes. Your rules.',price:5.5})}>Start building <span>+</span></button></div><div className="steps">{[['01','PICK A SIZE','Mini Treat, Regular, Large or Sharing Box.'],['02','CHOOSE A SAUCE','Chocolate, pistachio, Lotus & more.'],['03','MAKE IT YOURS','Fruit, crunch and premium extras.']].map(x=><div key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
      <section className="drinks"><div><p className="eyebrow">KEEP IT SIMPLE</p><h2>Drinks.</h2></div>{Object.entries(drinks).map(([group,items])=><div className="drink-list" key={group}><h3>{group}</h3>{items.map(item=><p key={item}>{item}</p>)}</div>)}</section>
      <section id="story" className="story"><div className="story-art"><div className="gold-orb">Z</div></div><div><p className="eyebrow">A TINY DUTCH CLASSIC</p><h2>Small by nature.<br/>Unforgettable by design.</h2><p>Poffertjes are soft, airy mini pancakes with a golden edge. At ZIPPOLINO, we make every batch fresh and turn it into something joyful, generous and unmistakably ours.</p><div className="values"><span><b>01</b>Freshly cooked</span><span><b>02</b>Quality toppings</span><span><b>03</b>Made for sharing</span></div></div></section>
      <section className="how"><p className="eyebrow">THREE SIMPLE STEPS</p><h2>Tap. Top. Collect.</h2><div>{[['01','Choose','Find your favourite or build your own.'],['02','Customise','Make every box exactly yours.'],['03','Collect','We’ll prepare it fresh for pickup.']].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
      <section id="visit" className="visit"><div><p className="eyebrow">COME FIND US</p><h2>Your next sweet moment starts here.</h2><p>Paphos, Cyprus · Exact pickup point and opening hours will appear here before launch.</p></div><a className="primary" href="#menu">Order for pickup <span>→</span></a></section>
    </main>
    <footer><a className="brand" href="#top"><span>Z</span>ZIPPOLINO</a><div><a href="#menu">Menu</a><a href="#story">About</a><a href="mailto:hello@zippolino.com">Email</a><a href="#privacy">Privacy</a></div><p>© {new Date().getFullYear()} ZIPPOLINO · ONLINE ORDERS ONLY</p></footer>
    {count>0&&<button className="mobile-bag" onClick={()=>setCartOpen(true)}>View bag · {count} {count===1?'item':'items'} <b>{money(subtotal)}</b></button>}
    {product&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setProduct(null)}><div className="modal"><button className="close" onClick={()=>setProduct(null)}>×</button><p className="eyebrow">MAKE IT YOURS</p><h2>{product.name}</h2><p>{product.note}</p>{['size','sauce','extra'].map(group=><fieldset key={group}><legend>{group==='extra'?'Finish with extras':group==='sauce'?'Choose sauces':'Choose size'}</legend>{options[group].map((o,i)=>{const single=group==='size',selected=single?choice.size===i:i===0?choice[group].length===0:choice[group].includes(i);return <label key={o[0]}><input type={single?'radio':'checkbox'} name={group} checked={selected} onChange={()=>single?setChoice(c=>({...c,size:i})):toggleChoice(group,i)}/><span>{o[0]}</span><b>{o[1]?`+${money(o[1])}`:single?'Included':'No charge'}</b></label>})}</fieldset>)}<label className="note">Special instructions<textarea value={choice.note} onChange={e=>setChoice(c=>({...c,note:e.target.value}))} placeholder="Allergies or requests?"/></label><div className="add-row"><div className="qty"><button onClick={()=>setChoice(c=>({...c,qty:Math.max(1,c.qty-1)}))}>−</button><b>{choice.qty}</b><button onClick={()=>setChoice(c=>({...c,qty:c.qty+1}))}>+</button></div><button className="primary" onClick={add}>Add to bag</button></div></div></div>}
    {cartOpen&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setCartOpen(false)}><aside className="drawer"><button className="close" onClick={()=>setCartOpen(false)}>×</button><p className="eyebrow">YOUR ORDER</p><h2>{checkout?'Checkout':'The good stuff.'}</h2>{!checkout?<>{cart.length===0?<div className="empty"><p>Your bag is waiting for something delicious.</p><button className="primary" onClick={()=>setCartOpen(false)}>Browse menu</button></div>:<><div className="cart-list">{cart.map(x=><div key={x.key}><div><h3>{x.qty} × {x.name}</h3><p>{x.size} · {x.sauce} · {x.extra}</p></div><b>{money(x.total)}</b><button onClick={()=>setCart(c=>c.filter(i=>i.key!==x.key))}>Remove</button></div>)}</div><div className="total"><span>Total</span><b>{money(subtotal)}</b></div><button className="primary full" onClick={()=>{setCheckout(true);event('begin_checkout',{value:subtotal})}}>Secure checkout →</button></>}</>:<form className="checkout" onSubmit={submitOrder}><label>Full name<input name="name" required autoComplete="name"/></label><label>Mobile number <small>for order updates only</small><input name="mobile" required type="tel" autoComplete="tel"/></label><label>Email<input name="email" required type="email" autoComplete="email"/></label><label>Pickup time<select name="pickup"><option>As soon as possible</option><option>In 30 minutes</option><option>In 45 minutes</option><option>In 60 minutes</option></select></label><label>Order notes<textarea name="notes" placeholder="Optional"/></label><div className="payment-note">🔒 Online payment is prepared for connection. Until Stripe/Viva credentials are added, this creates a test order without charging.</div><div className="total"><span>To pay</span><b>{money(subtotal)}</b></div><button className="primary full" type="submit">Place test order →</button><button className="back" type="button" onClick={()=>setCheckout(false)}>← Back to bag</button></form>}</aside></div>}
    {confirmation&&<div className="overlay"><div className="modal confirmation"><div className="check">✓</div><p className="eyebrow">ORDER RECEIVED</p><h2>Sweet choice.</h2><p>Your order <b>{confirmation.id}</b> is in the queue. This is a test confirmation until live payments and notifications are connected.</p><button className="primary" onClick={()=>setConfirmation(null)}>Done</button></div></div>}
  </>
}

function Orders(){const [orders,setOrders]=useState(()=>JSON.parse(localStorage.getItem('zippolino-orders')||'[]'));const update=(id,status)=>{const next=orders.map(o=>o.id===id?{...o,status}:o);setOrders(next);localStorage.setItem('zippolino-orders',JSON.stringify(next))};return <div className="admin"><header><a className="brand" href="#top"><span>Z</span>ZIPPOLINO</a><b>ORDER DESK</b><a href="#top">← Storefront</a></header><main><div className="section-head"><div><p className="eyebrow">KITCHEN VIEW</p><h1>Orders</h1></div><p>{orders.length} total · This device only until the live database is connected.</p></div>{orders.length===0?<div className="empty-admin"><h2>No orders yet.</h2><p>Place a test order from the storefront and it will appear here.</p><a className="primary" href="#top">Open storefront</a></div>:<div className="orders">{orders.map(o=><article key={o.id}><div><small>{new Date(o.createdAt).toLocaleString()}</small><h2>{o.id}</h2><p>{o.customer.name} · {o.customer.pickup}</p></div><b className={`status ${o.status.toLowerCase()}`}>{o.status}</b><ul>{o.items.map(x=><li key={x.key}>{x.qty} × {x.name} <span>{x.size} · {x.sauce} · {x.extra}</span></li>)}</ul><strong>{money(o.total)}</strong><div className="actions">{['Accepted','Preparing','Ready','Completed'].map(s=><button onClick={()=>update(o.id,s)} key={s}>{s}</button>)}</div></article>)}</div>}</main></div>}

createRoot(document.getElementById('root')).render(<App/>);
